name: Meu Workflow de Teste
on:
  push:
    branches: [ main ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Obter codigo fonte
      uses: actions/checkout@v4.2.2
      
    - name: Setup Java JDK
      uses: actions/setup-java@v3.14.1
      with:
        java-version: '11'
        distribution: oracle
        
    - name: Build .class
      working-directory: .
      run: javac HelloWordl.java

    - name: Rodar class
      working-directory: .
      run: java HelloWordl

  cd:
    runs-on: ubuntu-latest
    steps:
    - name: Preparar release
      run: echo "Preparando release"
    - run: echo "Executando etapa de build (simulada)"
